### ISSUE TITLE
[BUG] Fetch + service bindings = internal error

### ISSUE THREAD

**Issue by katopz** [cloudflare/workers-rs#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.12

## Refer 
https://community.cloudflare.com/t/fetch-service-bindings-internal-error/444599/15

When call service binding from pages I got "internal error".

## Reproduce
https://gist.rs/hello/test
https://49150712.gist-rs.pages.dev/hello/test

Current Deployment ID: `a93edc7e-86cc-42ba-ade8-ff324fea2f2d`
Account ID: `7e11517c4dd4f6e9cede7da9b60d66eb`

## Code
rust: https://github.com/gist-rs/gist-rs/blob/main/worker/web3lite/src/lib.rs#L39-L49
called from: https://github.com/gist-rs/gist-rs/blob/main/functions/hello/%5Btest%5D.ts

## Log
```
Connected to deployment 49150712-76c6-417f-82e3-fd5caa55f0db, waiting for logs...
GET https://gist.rs/hello/test - Exception Thrown @ 1/12/2023, 6:51:44 PM
✘ [ERROR]   Error: The script will never generate a response.


GET https://gist.rs/hello/test - Exception Thrown @ 1/12/2023, 6:51:44 PM
  (log) Thu Jan 12 2023 11:51:44 GMT+0000 (Coordinated Universal Time) - [/hello/test], located at: (13.7063, 100.4597), within: Bangkok
  (error) panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, source: "JsValue(Error: internal error\nError: internal error\n    at Wt (shim.js:492:16)\n    at wasm://wasm/002171de:wasm-function[464]:0x34217\n    at wasm://wasm/002171de:wasm-function[90]:0xad2f\n    at wasm://wasm/002171de:wasm-function[295]:0x2b1e8\n    at wasm://wasm/002171de:wasm-function[262]:0x28b44\n    at wasm://wasm/002171de:wasm-function[164]:0x1e661\n    at wasm://wasm/002171de:wasm-function[93]:0xce38\n    at wasm://wasm/002171de:wasm-function[171]:0x1f72e\n    at wasm://wasm/002171de:wasm-function[173]:0x1fada\n    at wasm://wasm/002171de:wasm-function[428]:0x3295d)" }', src/lib.rs:42:18

Stack:

Error
    at Z (shim.js:304:11)
    at wasm://wasm/002171de:wasm-function[300]:0x2b737
    at wasm://wasm/002171de:wasm-function[1659]:0x46b29
    at wasm://wasm/002171de:wasm-function[394]:0x30fe3
    at wasm://wasm/002171de:wasm-function[511]:0x35eeb
    at wasm://wasm/002171de:wasm-function[1224]:0x43f8e
    at wasm://wasm/002171de:wasm-function[797]:0x3dace
    at wasm://wasm/002171de:wasm-function[1059]:0x41fe7
    at wasm://wasm/002171de:wasm-function[595]:0x38bbf
    at wasm://wasm/002171de:wasm-function[164]:0x1e84e


✘ [ERROR]   Error: The script will never generate a response.
```

### Steps To Reproduce

1. Create pages with caller.
https://github.com/gist-rs/gist-rs/blob/main/functions/hello/%5Btest%5D.ts
```ts
export function onRequest(context) {
  return context.env.SERVICE.fetch(context.request, context);
}
```
2. Create Rust service binding. 
https://github.com/gist-rs/gist-rs/blob/main/worker/web3lite/src/lib.rs#L39-L49
```rust
use worker::*;

#[event(fetch)]
pub async fn main(req: Request, env: Env, _ctx: worker::Context) -> Result<Response> {
    let router = Router::new();

    router
        .get_async("/hello/:test", |_, _| async move {
            let body = reqwest::get("https://developers.cloudflare.com/")
                .await
                .unwrap()
                .text()
                .await
                .unwrap();

            console_log!("body: {body:?}");

            Response::ok("Hello from Workers!")
        })
        .run(req, env)
        .await
}
```
3. Call `service binding` to see an error https://49150712.gist-rs.pages.dev/hello/test

I'm pretty much stuck here with no easy workaround (also some lib depend on `reqwest` internally which mean I can't just replace `reqwest` with some other fetcher).

**Comment by WalshyDev** [comment]
This is now resolved, thanks for the report :)

Please do a new deployment and it should work correctly

**Comment by katopz** [comment]
> This is now resolved, thanks for the report :)
> 
> Please do a new deployment and it should work correctly

Confirm working fetch ref https://github.com/cloudflare/wrangler2/issues/2589

Thanks!

**Comment by gaberogan** [comment]
I'm still getting this error, using 3.22.1 (latest version is broken via issue 3259).

When I make any fetch request, it throws this error and no stack trace:

```
[wrangler:err] Error: internal error
```
