### ISSUE TITLE
worker-build v0.1.5 incompatible with wasm-bindgen 0.2.101 - experimental-reset-state-function flag error

### ISSUE THREAD

**Issue by alycda** [cloudflare/workers-rs#808]
### Version of `workers-rs`
0.1.5 (worker-build)

### Version of `wrangler`
4.37.1

### Description
`worker-build` v0.1.5 fails when building with the error:

```
error: unexpected argument '--experimental-reset-state-function' found
Usage: wasm-bindgen --out-dir <DIR> --typescript --target <TARGET> --out-name <VAR> <INPUT>
```

The issue occurs because:
- `worker-build` v0.1.5 passes the `--experimental-reset-state-function` flag to wasm-bindgen
- It installs wasm-bindgen 0.2.101 via wasm-pack, which doesn't support this flag
- The flag was only added in wasm-bindgen 0.2.102

This breaks the development workflow for anyone running `cargo clean` or doing fresh installs, as they get worker-build v0.1.5 which is incompatible.

### Steps to reproduce
1. Create a workers-rs project with this `wrangler.toml`:
   ```toml
   [build]
   command = "cargo install -q worker-build && worker-build --release"
   ```
2. Run `cargo clean` (forces reinstall of worker-build)
3. Run `npx wrangler dev`
4. Observe the wasm-bindgen error

**Workaround**: Downgrade to worker-build v0.1.4:
```bash
cargo install worker-build --version 0.1.4 --force
```

**Expected fix**: Either update worker-build v0.1.5 to use wasm-bindgen 0.2.102+, or remove the experimental flag until wasm-bindgen compatibility is ensured.

**Comment by PeterMHammond** [comment]
> ### Version of `workers-rs`
> 0.1.5 (worker-build)
> 
> ### Version of `wrangler`
> 4.37.1
> 
> ### Description
> `worker-build` v0.1.5 fails when building with the error:
> 
> ```
> error: unexpected argument '--experimental-reset-state-function' found
> Usage: wasm-bindgen --out-dir <DIR> --typescript --target <TARGET> --out-name <VAR> <INPUT>
> ```
> 
> The issue occurs because:
> 
> * `worker-build` v0.1.5 passes the `--experimental-reset-state-function` flag to wasm-bindgen
> * It installs wasm-bindgen 0.2.101 via wasm-pack, which doesn't support this flag
> * The flag was only added in wasm-bindgen 0.2.102
> 
> This breaks the development workflow for anyone running `cargo clean` or doing fresh installs, as they get worker-build v0.1.5 which is incompatible.
> 
> ### Steps to reproduce
> 1. Create a workers-rs project with this `wrangler.toml`:
>    [build]
>    command = "cargo install -q worker-build && worker-build --release"
> 2. Run `cargo clean` (forces reinstall of worker-build)
> 3. Run `npx wrangler dev`
> 4. Observe the wasm-bindgen error
> 
> **Workaround**: Downgrade to worker-build v0.1.4:
> 
> cargo install worker-build --version 0.1.4 --force
> **Expected fix**: Either update worker-build v0.1.5 to use wasm-bindgen 0.2.102+, or remove the experimental flag until wasm-bindgen compatibility is ensured.

Just upgraded - same exact problem.

**Comment by EmersonDove** [comment]
Same issue as well! 

This also appeared with the `v0.1.5` release but might deserve a different issue

```bash
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 38.94s
[INFO]: 📦   Your wasm pkg is ready to publish at rust/build.
✘ [ERROR] Expected "from" but found "wasmModule"

    index.js:1:14:
      1 │ import source wasmModule from "./index_bg.wasm";
        │               ~~~~~~~~~~
        ╵               from
```

Downgrading to 0.1.4 fixes the above and `--experimental-reset-state-function` errors

**Comment by lazyanubis** [comment]
Same issue

**Comment by kasimanatar-afk** [comment]
> Same issue as well!
> 
> This also appeared with the `v0.1.5` release but might deserve a different issue
> 
> [INFO]: Optimizing wasm binaries with `wasm-opt`...
> [INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
> [INFO]: ✨   Done in 38.94s
> [INFO]: 📦   Your wasm pkg is ready to publish at rust/build.
> ✘ [ERROR] Expected "from" but found "wasmModule"
> 
>     index.js:1:14:
>       1 │ import source wasmModule from "./index_bg.wasm";
>         │               ~~~~~~~~~~
>         ╵               from
> Downgrading to 0.1.4 fixes the above and `--experimental-reset-state-function` errors

This fixed it for me

**Comment by kasimanatar-afk** [comment]
if it persist, try to override [build] line from wrangler.*
the `wrangler dev` itself forcing `worker-build` back to version 0.0.15

**Comment by guybedford** [comment]
This should be resolved in the latest worker-build 0.1.6 now. Please do report back if there are further issues with the release here.

It is of course also recommended to update wasm-bindgen to latest too.

**Comment by DamonOehlman** [comment]
I'm still having issues after upgrading all versions, different error this time.  After diving into the source of the worker-build main.rs I'm wondering if these two statements are out of order based on what I'm seeing:

https://github.com/cloudflare/workers-rs/blob/eee69462296114849848f85db213da4eca5790c8/worker-build/src/main.rs#L107-L109

Reported error for context:

```
✘ [ERROR] Expected "from" but found "wasmModule"

    index.js:1:14:
      1 │ import source wasmModule from "./index_bg.wasm";
        │               ~~~~~~~~~~
        ╵               from
```

Feels like worker build is intending to deal with the `import source` statement with a text replacement, but attempting to apply it after esbuild runs and it's esbuild that's bailing out.  Not sure if I'm the only one seeing this issue though.

**Comment by omkhar** [comment]
I have the same issue

**Comment by aoifelee** [comment]
Also seeing the import error. My steps to reproduce are:
1. Run `cargo generate cloudflare/workers-rs`
2. Choose `template/hello-world`
3. Run `cargo install worker-build`
4. Run `worker-build --release`

Output:
```
Code/importtest (main) » worker-build --release
[INFO]: 🎯  Checking for the Wasm target...
Using global wasm-bindgen
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: 🌀  Compiling to Wasm...
    Finished `release` profile [optimized] target(s) in 0.05s
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 0.54s
[INFO]: 📦   Your wasm pkg is ready to publish at /Users/khy/Code/importtest/build.
✘ [ERROR] Expected "from" but found "wasmModule"

    index.js:1:14:
      1 │ import source wasmModule from "./index_bg.wasm";
        │               ~~~~~~~~~~
        ╵               from

1 error
Error: esbuild exited with status exit status: 1
```

**Comment by naidherng** [comment]
> Also seeing the import error. My steps to reproduce are:
> 
> 1. Run `cargo generate cloudflare/workers-rs`
> 2. Choose `template/hello-world`
> 3. Run `cargo install worker-build`
> 4. Run `worker-build --release`
> 
> Output:
> 
> ```
> Code/importtest (main) » worker-build --release
> [INFO]: 🎯  Checking for the Wasm target...
> Using global wasm-bindgen
> [INFO]: ⬇️  Installing wasm-bindgen...
> [INFO]: 🌀  Compiling to Wasm...
>     Finished `release` profile [optimized] target(s) in 0.05s
> [INFO]: Optimizing wasm binaries with `wasm-opt`...
> [INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
> [INFO]: ✨   Done in 0.54s
> [INFO]: 📦   Your wasm pkg is ready to publish at /Users/khy/Code/importtest/build.
> ✘ [ERROR] Expected "from" but found "wasmModule"
> 
>     index.js:1:14:
>       1 │ import source wasmModule from "./index_bg.wasm";
>         │               ~~~~~~~~~~
>         ╵               from
> 
> 1 error
> Error: esbuild exited with status exit status: 1
> ```
update wasm-bidgen to v 0.2.103
Same issue

**Comment by guybedford** [comment]
The remaining issue here was since fixed in https://github.com/cloudflare/workers-rs/pull/813 and released in 0.6.4. Please do report any further issues.

**Comment by naidherng** [comment]
> The remaining issue here was since fixed in [#813](https://github.com/cloudflare/workers-rs/pull/813) and released in 0.6.4. Please do report any further issues.

I'm try build with command "worker-build --release" it can build without error.
But when run with "npx wrangler dev" or "pnpm dlx wrangler dev" will show error below 

The file src changed, restarting build...
[custom build] Running: cargo install -q worker-build && worker-build --release
[custom build] [INFO]: 🎯  Checking for the Wasm target...
...
...
...
✘ [ERROR] Custom build failed: Error: Build failed with 1 error:

  build/index.js:1:69: ERROR: Expected "from" but found "M"
      at failureErrorWithLog
  (/home/naidherng/.npm/_npx/32026684e21afda6/node_modules/esbuild/lib/main.js:1463:15)
      at /home/naidherng/.npm/_npx/32026684e21afda6/node_modules/esbuild/lib/main.js:924:25
      at /home/naidherng/.npm/_npx/32026684e21afda6/node_modules/esbuild/lib/main.js:1341:9
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
    errors: [Getter/Setter],
    warnings: [Getter/Setter]
  }

✘ [ERROR] Build failed with 1 error:

  ✘ [ERROR] Expected "from" but found "M"
  
      build/index.js:1:69:
        1 │ ...oudflare:workers";import source M from"./index_bg.wasm";var r,g=...
          │                                    ^
          ╵                                    from
  
wrangler version 4.38.0

**Comment by PeterMHammond** [comment]
> > The remaining issue here was since fixed in [#813](https://github.com/cloudflare/workers-rs/pull/813) and released in 0.6.4. Please do report any further issues.
> 
> I'm try build with command "worker-build --release" it can build without error. But when run with "npx wrangler dev" or "pnpm dlx wrangler dev" will show error below
> 
> The file src changed, restarting build... [custom build] Running: cargo install -q worker-build && worker-build --release [custom build] [INFO]: 🎯 Checking for the Wasm target... ... ... ... ✘ [ERROR] Custom build failed: Error: Build failed with 1 error:
> 
> build/index.js:1:69: ERROR: Expected "from" but found "M" at failureErrorWithLog (/home/naidherng/.npm/_npx/32026684e21afda6/node_modules/esbuild/lib/main.js:1463:15) at /home/naidherng/.npm/_npx/32026684e21afda6/node_modules/esbuild/lib/main.js:924:25 at /home/naidherng/.npm/_npx/32026684e21afda6/node_modules/esbuild/lib/main.js:1341:9 at process.processTicksAndRejections (node:internal/process/task_queues:105:5) { errors: [Getter/Setter], warnings: [Getter/Setter] }
> 
> ✘ [ERROR] Build failed with 1 error:
> 
> ✘ [ERROR] Expected "from" but found "M"
> 
> ```
>   build/index.js:1:69:
>     1 │ ...oudflare:workers";import source M from"./index_bg.wasm";var r,g=...
>       │                                    ^
>       ╵                                    from
> ```
> 
> wrangler version 4.38.0

Same issue - had to revert to a custom build command to remove "source" to get it to start compiling again: 
`command = "cargo install -q worker-build && worker-build --release && sed -i 's/import source \\([a-zA-Z_][a-zA-Z0-9_]*\\) from/import \\1 from/g' build/index.js"
`

**Comment by guybedford** [comment]
Thanks, I have a new fix for this case, will post it out soon.

**Comment by guybedford** [comment]
(in the mean time you can disable minification)

**Comment by aoifelee** [comment]
I can wait for the fix, but out of curiosity, how does one disable minification?

**Comment by guybedford** [comment]
It should be ready in the next 30 mins anyway.

But you can use `NO_MINIFY=1` env var.

**Comment by PeterMHammond** [comment]
@guybedford - Thank you - it appears this issue has been put to rest.  Fully upgraded and everything is building without issues.
Really do appreciate your quick work on this.  As I launch at the end of the month - think I'll lock my versions here.  
I like being bleeding edge, but think I got just a little too close to the really pointy part that time.  🫠
